### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by jvorcak** [js-rcon/react-console-emulator#41]
Hi again :)

I think there is a last problem in a build process. And that is IE11 support.
Not even live demo works in IE11.
https://linuswillner.me/react-console-emulator/
![screen shot 2018-11-23 at 08 22 49](https://user-images.githubusercontent.com/1083817/48931875-ff75a400-eef8-11e8-9628-fcfb0e6ae357.png)

![screen shot 2018-11-23 at 07 57 48](https://user-images.githubusercontent.com/1083817/48931851-d1905f80-eef8-11e8-96ba-ec108d8ca870.png)

I think it's some kind of transpilation thing, the output contains `=>` which IE11 doesn't know about. Can you please have a look? I'm playing arout your babel configs, but so far no luck

**Comment by linuswillner** [comment]
You’re hitting the crux of the issue with supporting old browsers: Fix one problem, create another. But I’ll take a look regardless.

Feel free to report any progress you get which might help me forwards on this.

**Comment by linuswillner** [comment]
I've taken a look at this and come to the following conclusion.

In order to get the code IE11 compatible out of the box, I would have to Webpack the code that is distributed with this module. This would introduce unnecessary additional overhead as code that doesn't belong in the module would get involved. The minified output you're seeing in the screenshot is created by Webpack, which acts as the top-level development tool (Not package level which is where this project is sitting at).

In general this project uses fairly basic DOM concepts that to my knowledge work in IE as well. However, distributing IE-compatible code is not of my concern at this level.

I did make one change to the build process however. Starting with version 1.7.3, the distributed code will be compatible with a much wider range of Node versions thanks to module transpilation being enabled. Otherwise, this is a won't fix-case for my part.
